USE [master]
GO

/****** Object:  Database [eaw01]    Script Date: 01/16/2015 08:06:56 ******/
ALTER DATABASE eaw01
SET OFFLINE WITH ROLLBACK IMMEDIATE;

DROP DATABASE [eaw01];
GO

USE [master]
GO

/****** Object:  Database [eaw01]    Script Date: 01/16/2015 08:06:56 ******/
CREATE DATABASE [eaw01] ON  PRIMARY 
( NAME = N'eaw01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\eaw01.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'eaw01_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\eaw01_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [eaw01] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eaw01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eaw01] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eaw01] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eaw01] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eaw01] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eaw01] SET ARITHABORT OFF 
GO

ALTER DATABASE [eaw01] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eaw01] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [eaw01] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eaw01] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eaw01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eaw01] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eaw01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eaw01] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eaw01] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eaw01] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eaw01] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eaw01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eaw01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eaw01] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eaw01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eaw01] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eaw01] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eaw01] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eaw01] SET  READ_WRITE 
GO

ALTER DATABASE [eaw01] SET RECOVERY FULL 
GO

ALTER DATABASE [eaw01] SET  MULTI_USER 
GO

ALTER DATABASE [eaw01] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eaw01] SET DB_CHAINING OFF 
GO

/* Database creation is done, next create table*/

USE [eaw01]
GO
/****** Object:  Table [dbo].[STUDENT]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENT](
	[student_id] [nchar](10) NOT NULL,
	[classof_id] [int] NOT NULL,
	[name] [nvarchar](256) NOT NULL,
	[lastname] [nvarchar](512) NOT NULL,
	[email] [nvarchar](256) NOT NULL,
	[password] [nvarchar](256) NOT NULL,
	[profilepic] [nvarchar](256) NOT NULL,
	[GPA] [float] NOT NULL,
	[addeddate] [datetime] NOT NULL,
	[updatedate] [datetime] NULL,
	[student_status] [tinyint] NOT NULL,
 CONSTRAINT [PK_STUDENT] PRIMARY KEY CLUSTERED 
(
	[student_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLASSOF](
	[classof_id] [int] NOT NULL,
	[classof_description] [nchar](10) NOT NULL,
 CONSTRAINT [PK_CLASSOF] PRIMARY KEY CLUSTERED 
(
	[classof_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN_MEMBER]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN_MEMBER](
	[admin_id] [nchar](10) NOT NULL,
	[name] [nvarchar](256) NULL,
	[lastname] [nvarchar](512) NULL,
	[email] [nvarchar](256) NULL,
	[password] [nvarchar](256) NULL,
	[addeddate] [datetime] NULL,
	[updatedate] [datetime] NULL,
 CONSTRAINT [PK_ADMIN_MEMBER] PRIMARY KEY CLUSTERED 
(
	[admin_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBJECT]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBJECT](
	[subject_id] [nchar](10) NOT NULL,
	[name] [nvarchar](256) NOT NULL,
	[description] [text] NOT NULL,
	[defaultpoint] [float] NOT NULL,
	[addeddate] [datetime] NOT NULL,
	[updatedate] [datetime] NULL,
 CONSTRAINT [PK_SUBJECT] PRIMARY KEY CLUSTERED 
(
	[subject_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_ROLE]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_ROLE](
	[user_id] [nchar](10) NOT NULL,
	[role] [nvarchar](50) NOT NULL,
	[updatedate] [datetime] NOT NULL,
 CONSTRAINT [PK_USER_ROLE] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMP_SELECTION]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_SELECTION](
	[student_id] [nchar](10) NOT NULL,
	[subject_id] [nchar](10) NOT NULL,
	[classof_id] [int] NOT NULL,
	[semester] [nchar](10) NOT NULL,
	[status] [nvarchar](50) NOT NULL,
	[type] [nvarchar](50) NOT NULL,
	[addeddate] [datetime] NOT NULL,
 CONSTRAINT [PK_TMP_SELECTION] PRIMARY KEY CLUSTERED 
(
	[student_id] ASC,
	[subject_id] ASC,
	[classof_id] ASC,
	[semester] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBJECT_CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBJECT_CLASSOF](
	[subject_id] [nchar](10) NOT NULL,
	[classof_id] [int] NOT NULL,
	[semester] [nchar](10) NOT NULL,
	[minstudent] [int] NOT NULL,
	[maxstudent] [int] NOT NULL,
	[credit] [float] NOT NULL,
	[dayofweek] [int] NOT NULL,
	[timeofday] [int] NOT NULL,
	[instructor] [nvarchar](256) NOT NULL,
	[required] [bit] NOT NULL,
	[addeddate] [datetime] NOT NULL,
	[updatedate] [datetime] NULL,
 CONSTRAINT [PK_SUBJECT_CLASSOF] PRIMARY KEY CLUSTERED 
(
	[subject_id] ASC,
	[classof_id] ASC,
	[semester] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENT_ENROLLMENT]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENT_ENROLLMENT](
	[student_id] [nchar](10) NOT NULL,
	[subject_id] [nchar](10) NOT NULL,
	[classof_id] [int] NOT NULL,
	[semester] [nchar](10) NOT NULL,
	[addeddate] [datetime] NOT NULL,
 CONSTRAINT [PK_STUDENT_ENROLLMENT] PRIMARY KEY CLUSTERED 
(
	[student_id] ASC,
	[subject_id] ASC,
	[classof_id] ASC,
	[semester] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENT_CONFIRMED_ENROLLMENT]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT](
	[student_id] [nchar](10) NOT NULL,
	[subject_id] [nchar](10) NOT NULL,
	[classof_id] [int] NOT NULL,
	[semester_id] [nchar](10) NOT NULL,
	[addeddate] [datetime] NOT NULL,
 CONSTRAINT [PK_STUDENT_CONFIRMED_ENROLLMENT] PRIMARY KEY CLUSTERED 
(
	[student_id] ASC,
	[subject_id] ASC,
	[classof_id] ASC,
	[semester_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN_AUDITLOG]    Script Date: 01/12/2015 23:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN_AUDITLOG](
	[id] [int] NOT NULL,
	[user_id] [nchar](10) NOT NULL,
	[activity] [text] NOT NULL,
	[logdate] [datetime] NOT NULL,
 CONSTRAINT [PK_ADMIN_AUDITLOG] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_ADMIN_AUDITLOG_USER_ROLE]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[ADMIN_AUDITLOG]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_AUDITLOG_USER_ROLE] FOREIGN KEY([user_id])
REFERENCES [dbo].[USER_ROLE] ([user_id])
GO
ALTER TABLE [dbo].[ADMIN_AUDITLOG] CHECK CONSTRAINT [FK_ADMIN_AUDITLOG_USER_ROLE]
GO
/****** Object:  ForeignKey [FK_STUDENT_CONFIRMED_ENROLLMENT_CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_CLASSOF] FOREIGN KEY([classof_id])
REFERENCES [dbo].[CLASSOF] ([classof_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_CLASSOF]
GO
/****** Object:  ForeignKey [FK_STUDENT_CONFIRMED_ENROLLMENT_STUDENT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_STUDENT] FOREIGN KEY([student_id])
REFERENCES [dbo].[STUDENT] ([student_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_STUDENT]
GO
/****** Object:  ForeignKey [FK_STUDENT_CONFIRMED_ENROLLMENT_SUBJECT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_SUBJECT] FOREIGN KEY([subject_id])
REFERENCES [dbo].[SUBJECT] ([subject_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_CONFIRMED_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_CONFIRMED_ENROLLMENT_SUBJECT]
GO
/****** Object:  ForeignKey [FK_STUDENT_ENROLLMENT_CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_ENROLLMENT_CLASSOF] FOREIGN KEY([classof_id])
REFERENCES [dbo].[CLASSOF] ([classof_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_ENROLLMENT_CLASSOF]
GO
/****** Object:  ForeignKey [FK_STUDENT_ENROLLMENT_STUDENT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_ENROLLMENT_STUDENT] FOREIGN KEY([student_id])
REFERENCES [dbo].[STUDENT] ([student_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_ENROLLMENT_STUDENT]
GO
/****** Object:  ForeignKey [FK_STUDENT_ENROLLMENT_SUBJECT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[STUDENT_ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_ENROLLMENT_SUBJECT] FOREIGN KEY([subject_id])
REFERENCES [dbo].[SUBJECT] ([subject_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUDENT_ENROLLMENT] CHECK CONSTRAINT [FK_STUDENT_ENROLLMENT_SUBJECT]
GO
/****** Object:  ForeignKey [FK_SUBJECT_CLASSOF_CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[SUBJECT_CLASSOF]  WITH CHECK ADD  CONSTRAINT [FK_SUBJECT_CLASSOF_CLASSOF] FOREIGN KEY([classof_id])
REFERENCES [dbo].[CLASSOF] ([classof_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SUBJECT_CLASSOF] CHECK CONSTRAINT [FK_SUBJECT_CLASSOF_CLASSOF]
GO
/****** Object:  ForeignKey [FK_SUBJECT_CLASSOF_SUBJECT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[SUBJECT_CLASSOF]  WITH CHECK ADD  CONSTRAINT [FK_SUBJECT_CLASSOF_SUBJECT] FOREIGN KEY([subject_id])
REFERENCES [dbo].[SUBJECT] ([subject_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SUBJECT_CLASSOF] CHECK CONSTRAINT [FK_SUBJECT_CLASSOF_SUBJECT]
GO
/****** Object:  ForeignKey [FK_TMP_SELECTION_CLASSOF]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[TMP_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_TMP_SELECTION_CLASSOF] FOREIGN KEY([classof_id])
REFERENCES [dbo].[CLASSOF] ([classof_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMP_SELECTION] CHECK CONSTRAINT [FK_TMP_SELECTION_CLASSOF]
GO
/****** Object:  ForeignKey [FK_TMP_SELECTION_STUDENT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[TMP_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_TMP_SELECTION_STUDENT] FOREIGN KEY([student_id])
REFERENCES [dbo].[STUDENT] ([student_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMP_SELECTION] CHECK CONSTRAINT [FK_TMP_SELECTION_STUDENT]
GO
/****** Object:  ForeignKey [FK_TMP_SELECTION_SUBJECT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[TMP_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_TMP_SELECTION_SUBJECT] FOREIGN KEY([subject_id])
REFERENCES [dbo].[SUBJECT] ([subject_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMP_SELECTION] CHECK CONSTRAINT [FK_TMP_SELECTION_SUBJECT]
GO
/****** Object:  ForeignKey [FK_USER_ROLE_ADMIN_MEMBER]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE_ADMIN_MEMBER] FOREIGN KEY([user_id])
REFERENCES [dbo].[ADMIN_MEMBER] ([admin_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLE] CHECK CONSTRAINT [FK_USER_ROLE_ADMIN_MEMBER]
GO
/****** Object:  ForeignKey [FK_USER_ROLE_STUDENT]    Script Date: 01/12/2015 23:44:56 ******/
ALTER TABLE [dbo].[USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE_STUDENT] FOREIGN KEY([user_id])
REFERENCES [dbo].[STUDENT] ([student_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLE] CHECK CONSTRAINT [FK_USER_ROLE_STUDENT]
GO
